In [1]:
import pandas as pd

data_set = pd.read_csv("data/knn_customer_purchase.csv")
data_set.head(5)

,Customer_ID,Age,Gender,Years_Experience,Annual_Income,Spending_Score,City,Purchased
0,1,19,Male,22,18000.0,25,Kolkata,No
1,2,21,Female,25,22000.0,35,Kolkata,No
2,3,23,Male,28,28000.0,45,Newtown,No
3,4,25,Female,31,35000.0,60,Newtown,Yes
4,5,27,Male,34,42000.0,72,SaltLake,Yes

In [2]:
data_set.shape

(41, 8)

In [3]:
data_set.isnull().sum()

Customer_ID         0
Age                 0
Gender              1
Years_Experience    0
Annual_Income       1
Spending_Score      0
City                0
Purchased           0
dtype: int64

In [4]:
data_set.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       41 non-null     int64
 1   Age               41 non-null     int64
 2   Gender            40 non-null     str
 3   Years_Experience  41 non-null     int64
 4   Annual_Income     40 non-null     float64
 5   Spending_Score    41 non-null     int64
 6   City              41 non-null     str
 7   Purchased         41 non-null     str
dtypes: float64(1), int64(4), str(3)
memory usage: 2.7 KB

In [5]:
data_set['Annual_Income'] = data_set['Annual_Income'].fillna(data_set['Annual_Income'].mean())
data_set['Gender'] = data_set['Gender'].fillna(data_set['Gender'].mode()[0])

data_set.isnull().sum()

Customer_ID         0
Age                 0
Gender              0
Years_Experience    0
Annual_Income       0
Spending_Score      0
City                0
Purchased           0
dtype: int64

In [7]:
data_set.duplicated().sum()

np.int64(1)

In [11]:
data_set.drop_duplicates(inplace=True)
data_set.duplicated().sum()

np.int64(0)

In [15]:
# convert string values into numerical values

data_set_numaric = pd.get_dummies(data_set, columns=['Gender', 'City', 'Purchased'])
data_set_numaric.head(5)

,Customer_ID,Age,Years_Experience,Annual_Income,Spending_Score,Gender_Female,Gender_Male,City_Kolkata,City_Newtown,City_SaltLake,Purchased_No,Purchased_Yes
0,1,19,22,18000.0,25,False,True,True,False,False,True,False
1,2,21,25,22000.0,35,True,False,True,False,False,True,False
2,3,23,28,28000.0,45,False,True,False,True,False,True,False
3,4,25,31,35000.0,60,True,False,False,True,False,False,True
4,5,27,34,42000.0,72,False,True,False,False,True,False,True

In [19]:
data_set_numaric.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       40 non-null     int64
 1   Age               40 non-null     int64
 2   Years_Experience  40 non-null     int64
 3   Annual_Income     40 non-null     float64
 4   Spending_Score    40 non-null     int64
 5   Gender_Female     40 non-null     bool
 6   Gender_Male       40 non-null     bool
 7   City_Kolkata      40 non-null     bool
 8   City_Newtown      40 non-null     bool
 9   City_SaltLake     40 non-null     bool
 10  Purchased_No      40 non-null     bool
 11  Purchased_Yes     40 non-null     bool
dtypes: bool(7), float64(1), int64(4)
memory usage: 2.0 KB

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = data_set_numaric.drop(columns=['Purchased_No', 'Purchased_Yes', 'Customer_ID'])
Y = data_set_numaric['Purchased_Yes'].astype(int)

x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.3, random_state=0, stratify=Y
)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_train

array([[ 0.79703947,  0.71512216,  0.80117909,  0.79678801, -1.07417231,
         1.07417231, -0.52223297, -0.8660254 ,  1.34164079],
       [-0.72773169, -0.67688033, -0.7137509 , -0.29766797,  0.93094934,
        -0.93094934, -0.52223297,  1.15470054, -0.74535599],
       [-0.31188501, -0.03441764, -0.34649515, -0.17138459,  0.93094934,
        -0.93094934, -0.52223297, -0.8660254 ,  1.34164079],
       [-0.03465389,  0.07265947,  0.06666758,  0.3758434 , -1.07417231,
         1.07417231, -0.52223297, -0.8660254 ,  1.34164079],
       [ 0.65842391,  0.50096793,  0.57164424,  0.71259909, -1.07417231,
         1.07417231, -0.52223297, -0.8660254 ,  1.34164079],
       [ 0.93565503,  1.25050773,  1.0766209 ,  0.83888247,  0.93094934,
        -0.93094934, -0.52223297, -0.8660254 ,  1.34164079],
       [-1.00496281, -1.10518879, -1.08100666, -1.22374611,  0.93094934,
        -0.93094934,  1.91485422, -0.8660254 , -0.74535599],
       [-0.31188501, -0.24857187, -0.25468121,  0.03908771,  0.93094934,
        -0.93094934, -0.52223297, -0.8660254 ,  1.34164079],
       [-0.72773169, -0.4627261 , -0.66784393, -0.38185689, -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [ 0.38119279,  0.39389081,  0.43392333,  0.62841016,  0.93094934,
        -0.93094934, -0.52223297,  1.15470054, -0.74535599],
       [ 0.38119279,  0.2868137 ,  0.38801636,  0.5863157 , -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [ 1.49011727,  1.67881619,  1.48978363,  1.09144923,  0.93094934,
        -0.93094934, -0.52223297, -0.8660254 ,  1.34164079],
       [-0.86634725, -0.99811167, -0.98919272, -1.13955719,  0.93094934,
        -0.93094934,  1.91485422, -0.8660254 , -0.74535599],
       [-0.03465389, -0.35564899, -0.20877424,  0.12327663,  0.93094934,
        -0.93094934, -0.52223297, -0.8660254 ,  1.34164079],
       [ 0.51980835,  0.60804504,  0.66345818,  0.96516585,  0.93094934,
        -0.93094934, -0.52223297, -0.8660254 ,  1.34164079],
       [-1.28219393, -1.31934302, -1.3105415 , -1.35002949,  0.93094934,
        -0.93094934,  1.91485422, -0.8660254 , -0.74535599],
       [-0.58911613, -0.78395744, -0.80556484, -0.63442366,  0.93094934,
        -0.93094934, -0.52223297,  1.15470054, -0.74535599],
       [-1.00496281, -0.99811167, -1.03509969, -0.92908488, -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [ 0.24257723,  0.17973658,  0.20438848,  0.46003232,  0.93094934,
        -0.93094934, -0.52223297,  1.15470054, -0.74535599],
       [ 2.04457951,  1.57173907,  1.81113241,  1.17563815, -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [-1.14357837, -1.2122659 , -1.21872756, -1.56050179, -1.07417231,
         1.07417231,  1.91485422, -0.8660254 , -0.74535599],
       [ 1.90596395,  1.46466196,  1.58159756,  1.13354369, -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [ 0.10396167,  0.82219927,  0.4798303 ,  0.50212678, -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [-1.42080949, -1.64057436, -1.51712287, -2.06563532, -1.07417231,
         1.07417231,  1.91485422, -0.8660254 , -0.74535599],
       [ 0.10396167,  0.2868137 ,  0.34210939,  0.75469355, -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [-0.17326945, -0.03441764, -0.07851321,  0.54422124,  0.93094934,
        -0.93094934, -0.52223297, -0.8660254 ,  1.34164079],
       [ 1.76734839,  1.7858933 ,  1.90294635,  1.21773261, -1.07417231,
         1.07417231, -0.52223297,  1.15470054, -0.74535599],
       [-1.69804061, -1.74765147, -1.58598332, -2.1919187 ,  0.93094934,
        -0.93094934,  1.91485422, -0.8660254 , -0.74535599]])

In [31]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

df = pd.DataFrame({ "Actual": y_test, "Prediction": y_pred })
df

    Actual  Prediction
23       1           1
9        1           1
18       1           1
4        1           1
13       1           1
0        0           0
10       0           0
8        1           1
26       1           1
12       0           1
28       0           0
36       1           1

In [32]:
from sklearn.metrics import accuracy_score, f1_score

print("Accuracy: ", accuracy_score(y_test, y_pred))
print("F1 Score: ", f1_score(y_test, y_pred))

Accuracy:  0.9166666666666666
F1 Score:  0.9411764705882353