In [1]:
import pandas as pd

row_data_set = pd.read_csv("../Data/Row/student_placement_Data.csv")
row_data_set.shape

(100000, 18)

In [4]:
row_data_set.head(10)

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42
5,CSE,Tier-3,6.21,1,6.7,6.5,69.9,5.0,4.0,5.2,2,3,3,2,0,1,1,16.47
6,CSE,Tier-3,7.91,0,7.0,3.9,61.5,6.7,4.9,2.2,2,5,2,1,0,3,1,16.51
7,IT,Tier-3,6.95,0,6.1,6.0,44.4,5.5,4.5,6.3,1,2,1,1,1,0,0,NaN
8,CE,Tier-2,7.03,0,5.1,2.5,54.7,6.4,6.2,3.2,1,3,0,3,0,1,1,13.49
9,EE,Tier-2,7.34,3,4.7,6.2,78.8,5.9,6.7,5.2,1,2,1,1,0,0,1,17.95

In [5]:
row_data_set.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   branch                     100000 non-null  str
 1   college_tier               100000 non-null  str
 2   cgpa                       100000 non-null  float64
 3   backlogs                   100000 non-null  int64
 4   coding_skills              100000 non-null  float64
 5   dsa_score                  100000 non-null  float64
 6   aptitude_score             100000 non-null  float64
 7   communication_skills       100000 non-null  float64
 8   ml_knowledge               100000 non-null  float64
 9   system_design              100000 non-null  float64
 10  internships                100000 non-null  int64
 11  projects_count             100000 non-null  int64
 12  certifications             100000 non-null  int64
 13  hackathons                 100000 non-null  int64
 14  open_source_contributions  100000 non-null  int64
 15  extracurriculars           100000 non-null  int64
 16  placement_status           100000 non-null  int64
 17  salary_package_lpa         68475 non-null   float64
dtypes: float64(8), int64(8), str(2)
memory usage: 13.7 MB

In [6]:
row_data_set.describe()

,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,68475.000000
mean,7.206381,0.547010,5.995147,5.500711,64.990511,5.990614,4.508752,4.008210,1.095040,2.397280,1.49985,0.745840,0.450990,1.151100,0.684750,17.308014
std,0.925235,0.862727,1.496302,1.781961,11.990892,1.496552,1.968278,1.778405,0.940264,1.242829,1.11407,0.884189,0.671061,0.965162,0.464618,2.601041
min,4.000000,0.000000,1.000000,1.000000,20.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,6.880000
25%,6.580000,0.000000,5.000000,4.300000,56.800000,5.000000,3.200000,2.800000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,15.530000
50%,7.210000,0.000000,6.000000,5.500000,65.000000,6.000000,4.500000,4.000000,1.000000,2.000000,1.00000,0.000000,0.000000,1.000000,1.000000,17.250000
75%,7.830000,1.000000,7.000000,6.700000,73.100000,7.000000,5.900000,5.200000,2.000000,3.000000,2.00000,1.000000,1.000000,2.000000,1.000000,19.040000
max,10.000000,3.000000,10.000000,10.000000,100.000000,10.000000,10.000000,10.000000,3.000000,5.000000,4.00000,3.000000,2.000000,3.000000,1.000000,28.330000

In [7]:
row_data_set.isnull().sum()

branch                           0
college_tier                     0
cgpa                             0
backlogs                         0
coding_skills                    0
dsa_score                        0
aptitude_score                   0
communication_skills             0
ml_knowledge                     0
system_design                    0
internships                      0
projects_count                   0
certifications                   0
hackathons                       0
open_source_contributions        0
extracurriculars                 0
placement_status                 0
salary_package_lpa           31525
dtype: int64

In [9]:
row_data_set.duplicated().sum()

np.int64(0)

In [17]:
#check the outliners
numerical_data = row_data_set.select_dtypes("number").columns

Q1 = row_data_set[numerical_data].quantile(0.25)
Q3 = row_data_set[numerical_data].quantile(0.75)

IQR = Q3 - Q1

outlier_mask = (
    row_data_set[numerical_data] < (Q1 - 1.5 * IQR)) | (row_data_set[numerical_data] > (Q3 + 1.5 * IQR)
)

all_outlier_mask = row_data_set[outlier_mask.any(axis=1)]
all_outlier_mask.shape

(16880, 18)

In [2]:
branches = set(row_data_set['branch'])
branches

{'CE', 'CSE', 'Chemical', 'ECE', 'EE', 'IT', 'ME'}

In [4]:
college_tires = set(row_data_set['college_tier'])
college_tires

{'Tier-1', 'Tier-2', 'Tier-3'}