In [36]:
import pandas as pd

row_data_set = pd.read_csv("../Data/Row/student_placement_Data.csv")
row_data_set.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   branch                     100000 non-null  str
 1   college_tier               100000 non-null  str
 2   cgpa                       100000 non-null  float64
 3   backlogs                   100000 non-null  int64
 4   coding_skills              100000 non-null  float64
 5   dsa_score                  100000 non-null  float64
 6   aptitude_score             100000 non-null  float64
 7   communication_skills       100000 non-null  float64
 8   ml_knowledge               100000 non-null  float64
 9   system_design              100000 non-null  float64
 10  internships                100000 non-null  int64
 11  projects_count             100000 non-null  int64
 12  certifications             100000 non-null  int64
 13  hackathons                 100000 non-null  int64
 14  open_source_contributions  100000 non-null  int64
 15  extracurriculars           100000 non-null  int64
 16  placement_status           100000 non-null  int64
 17  salary_package_lpa         68475 non-null   float64
dtypes: float64(8), int64(8), str(2)
memory usage: 13.7 MB

In [37]:
# remove outliers
all_numeric_data_set = row_data_set.select_dtypes("number").columns

Q1 = row_data_set[all_numeric_data_set].quantile(0.25)
Q3 = row_data_set[all_numeric_data_set].quantile(0.75)

IQR = Q3 - Q1

outlier_mask = (
    (row_data_set[all_numeric_data_set] < (Q1 - 1.5 * IQR))
    | (row_data_set[all_numeric_data_set] > (Q3 + 1.5 * IQR))
)

all_outliers = row_data_set[outlier_mask.any(axis=1)]

row_data_set.drop(index=all_outliers.index, inplace=True)
row_data_set.shape

(83120, 18)

In [38]:
row_data_set['salary_package_lpa'].isnull().sum()

np.int64(26335)

In [39]:
row_data_set['salary_package_lpa'] = row_data_set['salary_package_lpa'].fillna(0).astype(int)
row_data_set.head(5)

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,0
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,0
5,CSE,Tier-3,6.21,1,6.7,6.5,69.9,5.0,4.0,5.2,2,3,3,2,0,1,1,16
6,CSE,Tier-3,7.91,0,7.0,3.9,61.5,6.7,4.9,2.2,2,5,2,1,0,3,1,16

In [40]:
all_categorical_data_types = row_data_set.select_dtypes("string").columns
all_categorical_data_types

Index(['branch', 'college_tier'], dtype='str')

In [41]:
row_data_set["branch_code"] = row_data_set["branch"].astype("category").cat.codes
row_data_set["college_tier_code"] = row_data_set["college_tier"].astype("category").cat.codes

row_data_set.head(3)

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa,branch_code,college_tier_code
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,0,2,1
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19,4,1
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,0,0,1

In [42]:
row_data_set.to_csv("../Data/Processed/processed_student_data_set.csv")
new_data_set = pd.read_csv("../Data/Processed/processed_student_data_set.csv")
new_data_set.isnull().sum()

Unnamed: 0                   0
branch                       0
college_tier                 0
cgpa                         0
backlogs                     0
coding_skills                0
dsa_score                    0
aptitude_score               0
communication_skills         0
ml_knowledge                 0
system_design                0
internships                  0
projects_count               0
certifications               0
hackathons                   0
open_source_contributions    0
extracurriculars             0
placement_status             0
salary_package_lpa           0
branch_code                  0
college_tier_code            0
dtype: int64